# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

gradle-curseforge-publish.interop.fabric-loom=false
gradle-curseforge-publish.interop.forge-gradle=false
gradle-curseforge-publish.interop.neoforged=false
gradle-curseforge-publish.interop.neogradle=false

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=26.1
yarn_mappings=26.1+build.1
loader_version=0.18.4

# Mod Properties
mod_version = 0.2.0+beta.7
maven_group = com.ishland.vmp
archives_base_name = vmp-fabric

# Dependencies
#fabric_version=0.41.0+1.17
async_util_version=0.1.0
